### ISSUE TITLE
Implement a sample WebSocket

### ISSUE THREAD

**Issue by RTG2717** [RTG2717/iso-chidiya-uddi#3]
Let's start with the harder part ig... me myself and many others working on this repo too have probably never used web sockets, so let's try implementing some sample web sockets. Anyone is welcome to complete this issue, I will also try to work on this when I get time.

**Comment by RTG2717** [comment]
Let's work on this after a single player prototype is ready!

**Comment by Digit4** [comment]
Check PR #5  @RTG2717
