### ISSUE TITLE
Add game (rules) logic for round timings, bird names, finger up-down logic, etc.

### ISSUE THREAD

**Issue by RTG2717** [RTG2717/iso-chidiya-uddi#7]

**Comment by Digit4** [comment]
Can we get a description of what the finger up/down logic will be? I will start working on it. #8 comment indicates using sliders for it, personally I think just buttons should be good enough, sliders will be bad UI.

**Comment by RTG2717** [comment]
Sliders were decided to increase a bit of randomness/chaos into the game. It can be bad UI but the main motive is not to make a fair game but to make chaos wherever possible.

There will be a vertical slider which if taken up above more than 69% will mark the finger as up for that specific chidiya and it can't be brought down now. Within 2 seconds, a player will have see the name of chidiya and move the slider up if they want to, and also bring the slider back down to prevent the finger up being noted again for the next chidiya.

Other idea was to have a button which whenever user releases then finger is considered up, this can have issues on phones (for eg: screen getting scrolled up/down when moving fingers too fast).

For the backend it's a simple message or up/down, if up is sent to backend then post the finger up msg to all other players, and same if finger down is sent. Sliders and buttons are a frontend choice, we can try both out and keep whichever feels better later.

**Comment by RTG2717** [comment]
Wait for some time though @Digit4 , I am working on this rn, I will edit both frontend and backend code to support this, and also add some flowchart about the game logic.

**Comment by Digit4** [comment]
Cool. If you're editing backend make a seperate file and import, otherwise there might be merge conflicts with my upcoming changes.
